import dotenv from "dotenv";
dotenv.config();

export const {
  CLIENT_APP_URL,
  APP_SECRET,
  PORT,
  APP_ENV,
  APP_URL,
  DATABASE_URL,
  SENTRY_DSN_URL,
  ACCESS_TOKEN_SECRET_KEY,
  REFRESH_TOKEN_SECRET_KEY,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  EMAIL_REFRESH_TOKEN,
  REDIRECT_URI,
  CLIENT_EMAIL,
  EMAIL_CLIENT_SECRET,
  EMAIL_CLIENT_ID,
} = process.env;
